#!/usr/bin/env bash

sudo pacman -Syu
sudo pacman -S git ripgrep pavucontrol xclip jq tldr shutter python3-pip

git clone git@github.com:junegunn/fzf.git $HOME/personal/fzf
$HOME/personal/fzf/install
